version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/horizonhome
      - SECRET_KEY=your-secret-key-please-change-in-production
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=horizonhome
    restart: always

volumes:
  postgres_data: