"""Update models

Revision ID: b3ea4f92e006
Revises: 2ab4f457fb8c
Create Date: 2025-04-09 23:28:01.135591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3ea4f92e006'
down_revision: Union[str, None] = '2ab4f457fb8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('properties', 'labels',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               postgresql_using='labels::json',  # Add this line
               existing_nullable=True)
    # Rest of the function remains the same
    op.add_column('property_preferences', sa.Column('tenant_profile_id', sa.Integer(), nullable=False))
    op.drop_constraint('property_preferences_preference_id_fkey', 'property_preferences', type_='foreignkey')
    op.create_foreign_key(None, 'property_preferences', 'tenant_profiles', ['tenant_profile_id'], ['id'])
    op.drop_column('property_preferences', 'preference_id')
    op.add_column('roommate_preferences', sa.Column('tenant_profile_id', sa.Integer(), nullable=False))
    op.drop_constraint('roommate_preferences_preference_id_fkey', 'roommate_preferences', type_='foreignkey')
    op.create_foreign_key(None, 'roommate_preferences', 'tenant_profiles', ['tenant_profile_id'], ['id'])
    op.drop_column('roommate_preferences', 'preference_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roommate_preferences', sa.Column('preference_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'roommate_preferences', type_='foreignkey')
    op.create_foreign_key('roommate_preferences_preference_id_fkey', 'roommate_preferences', 'user_preferences', ['preference_id'], ['id'])
    op.drop_column('roommate_preferences', 'tenant_profile_id')
    op.add_column('property_preferences', sa.Column('preference_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'property_preferences', type_='foreignkey')
    op.create_foreign_key('property_preferences_preference_id_fkey', 'property_preferences', 'user_preferences', ['preference_id'], ['id'])
    op.drop_column('property_preferences', 'tenant_profile_id')
    op.alter_column('properties', 'labels',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
